[package]
name = "dsp"
version = "0.0.1"
authors = ["Manuel Deval <manuel.deval@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.3"
itertools = "0.10.0"
hound = "3.4.0"
thiserror= "1.0.24"
rosc = "0.5.1"
crossbeam = "0.8.0"
fastrand= "1.4.0"

[lib]
path="src/lib.rs"
